### ISSUE TITLE
SSID mit Lehrzeichen wird nicht angenommen

### ISSUE THREAD

**Issue by TomCatShS** [ErikDorstel/SX1278POCSAG#8]
Hallo,

Sobald ich über set ssid XXXXX 2G eingebe wird nur WLAN SSID: 2G zurückgegeben. 

Möglichkeit um das problem zu umgehen ?

Gruß

**Comment by ErikDorstel** [comment]
Aktuell werden keine Leerzeichen unterstützt.

Lösung: Ersetze Zeile 39 in CLI.h https://github.com/ErikDorstel/SX1278POCSAG/blob/main/CLI.h#L39 durch:

```
int v1=cmdLine.indexOf(" ")+1;
int v2=cmdLine.indexOf(" ",v1)+1;
String value=cmdLine.substring(max(v1,v2));
```

**Comment by ErikDorstel** [comment]
Keine Reaktion vom Ersteller ... wird geschloßen.
